name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.SECRET_NAME }}" > "$HOME/.ssh/SECRET_NAME"
      - run: chmod 600 "$HOME/.ssh/key"
      # Deploy
      - run: cd app && rsync -e "ssh -p 20022 -i $HOME/.ssh/SECRET_NAME -o StrictHostKeyChecking=no" --archive --compress --delete . g107035.hostde32.fornex.host:/home/g107035/public_html/gretyll.io
